In [1]:
import pandas as pd

#Dataframes for each CSV File

df_agencies= pd.read_csv("agencies.csv") 
df_act_type = pd.read_csv("NIBRS_CRIMINAL_ACT_TYPE.csv")
df_act = pd.read_csv("NIBRS_CRIMINAL_ACT.csv")
df_incident = pd.read_csv("NIBRS_incident.csv")
df_location = pd.read_csv("NIBRS_LOCATION_TYPE.csv")
df_month = pd.read_csv("NIBRS_month.csv")
df_offense_type = pd.read_csv("NIBRS_OFFENSE_TYPE.csv")
df_offense = pd.read_csv("NIBRS_OFFENSE.csv")

df = df_incident\
    .merge(df_agencies, on="agency_id", how="inner")\
    .merge(df_month, on="did", how="inner")\
    .merge(df_offense, on="incident_id", how="inner", suffixes=("_left", "_right"))\
    .merge(df_offense_type, on="offense_code", how="inner")\
    .merge(df_act, on="offense_id", how="inner")\
    .merge(df_act_type, on="criminal_act_id", how="inner")\
    .merge(df_location, on="location_id", how = "inner")

df.to_csv("2021_merged_data.csv", index=False)

##### Removing Duplicates (If Any)

In [2]:
column_names = df.columns.tolist()
print("Number of Rows before removing duplicates: ", len(df))
df.drop_duplicates(subset=column_names, keep='first', inplace=True)
print('Number of Rows after removing Duplicates:', len(df))

Number of Rows before removing duplicates:  17474
Number of Rows after removing Duplicates: 17474

##### Removing Columns with Nulls or No Purpose

In [3]:
test = df.isna().sum()
for col, count in test.items():
    if count != 0:
        print(col, count)

cleared_except_date 17458
data_home_x 17474
covered_by_legacy_ori 17474
dormant_year 17474
ncic_agency_name 71
pub_agency_unit 17471
summary_rape_def 17474
report_date 16289
update_flag 17474
data_home_y 17474
month_pub_status 17474
num_premises_entered 17474
method_entry_code 17474

In [4]:
#These Columns had Null Entries
df.drop(columns=["cleared_except_date", 'data_home_x', 'covered_by_legacy_ori', 'dormant_year',\
                 'pub_agency_unit', 'report_date', 'update_flag', 'data_home_y', 'month_pub_status',\
                 'num_premises_entered', 'summary_rape_def', 'method_entry_code'], inplace=True)

#Manually Inspected The CSV
df.drop(columns=['nibrs_month_id_x', 'cargo_theft_flag', 'submission_date', 'report_date_flag', 'incident_id',\
                 'cleared_except_id', 'incident_status', 'orig_format_x', 'did', 'data_year_y', 'legacy_ori',\
                 'direct_contributor_flag', 'dormant_flag', 'reporting_type', 'ucr_agency_name', 'nibrs_month_id_x',\
                 'agency_status', 'state_id', 'state_abbr', 'state_postal_abbr', 'division_code', 'division_name',\
                 'region_code', 'region_name', 'region_desc', 'agency_type_name', 'submitting_agency_id', 'sai', 'ori',\
                 'submitting_agency_name', 'suburban_area_flag', 'population_group_id', 'population_group_code', 'yearly_agency_id',\
                 'population_group_desc', 'parent_pop_group_code', 'parent_pop_group_desc', 'mip_flag', 'pop_sort_order',\
                 'pe_reported_flag', 'officer_rate', 'employee_rate', 'nibrs_cert_date', 'nibrs_start_date', 'nibrs_leoka_start_date',\
                 'nibrs_ct_start_date',	'nibrs_multi_bias_start_date', 'nibrs_off_eth_start_date', 'covered_flag', 'county_name',\
                 'msa_name', 'publishable_flag', 'participated', 'nibrs_participated', 'data_year_left', 'nibrs_month_id_y',\
                 'agency_id_y',	'month_num', 'inc_data_year', 'reported_status', 'orig_format_y', 'ddocname', 'data_year_right',\
                 'offense_id', 'offense_code', 'attempt_complete_flag', 'location_id', 'ct_flag', 'hc_flag', 'hc_code', 'crime_against', \
                 'offense_group', 'data_year', 'criminal_act_id', 'criminal_act_code', 'criminal_act_desc', 'ncic_agency_name', 'location_code'],
                 inplace = True)

df.rename(columns={'data_year_x': 'year'}, inplace=True)
df.rename(columns={'agency_id_x': 'agency_location'}, inplace=True)
df.rename(columns={'pub_agency_name': 'agency_name'}, inplace=True)
df.rename(columns={'state_name': 'state'}, inplace=True)
df.rename(columns={'location_name': 'location_area'}, inplace=True)

#ncic_agency_name

##### Check Datatype for each Variable. Change Date Datatype.

In [5]:
df.info()
df['incident_date'] = pd.to_datetime(df['incident_date'], format='%Y-%m-%d', errors='coerce')
print("\n")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17474 entries, 0 to 17473
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   year                            17474 non-null  int64
 1   agency_location                 17474 non-null  int64
 2   incident_date                   17474 non-null  object
 3   incident_hour                   17474 non-null  int64
 4   agency_name                     17474 non-null  object
 5   state                           17474 non-null  object
 6   population                      17474 non-null  int64
 7   male_officer                    17474 non-null  int64
 8   male_civilian                   17474 non-null  int64
 9   male_officer+male_civilian      17474 non-null  int64
 10  female_officer                  17474 non-null  int64
 11  female_civilian                 17474 non-null  int64
 12  female_officer+female_civilian  17474 non-null  int64
 13  offense_name                    17474 non-null  object
 14  offense_category_name           17474 non-null  object
 15  criminal_act_name               17474 non-null  object
 16  location_area                   17474 non-null  object
dtypes: int64(10), object(7)
memory usage: 2.3+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17474 entries, 0 to 17473
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   year                            17474 non-null  int64
 1   agency_location                 17474 non-null  int64
 2   incident_date                   17474 non-null  datetime64[ns]
 3   incident_hour                   17474 non-null  int64
 4   agency_name                     17474 non-null  object
 5   state                           17474 non-null  object
 6   population                      17474 non-null  int64
 7   male_officer                    17474 non-null  int64
 8   male_civilian                   17474 non-null  int64
 9   male_officer+male_civilian      17474 non-null  int64
 10  female_officer                  17474 non-null  int64
 11  female_civilian                 17474 non-null  int64
 12  female_officer+female_civilian  17474 non-null  int64
 13  offense_name                    17474 non-null  object
 14  offense_category_name           17474 non-null  object
 15  criminal_act_name               17474 non-null  object
 16  location_area                   17474 non-null  object
dtypes: datetime64[ns](1), int64(10), object(6)
memory usage: 2.3+ MB

In [6]:
df.to_csv("2021_merged_data.csv", index=False)

In [7]:
df

,year,agency_location,incident_date,incident_hour,agency_name,state,population,male_officer,male_civilian,male_officer+male_civilian,female_officer,female_civilian,female_officer+female_civilian,offense_name,offense_category_name,criminal_act_name,location_area
0,2021,2120,2021-01-05,13,Ansonia,Connecticut,18452,32,1,33,6,9,15,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Highway/Road/Alley/Street/Sidewalk
1,2021,2120,2021-01-09,6,Ansonia,Connecticut,18452,32,1,33,6,9,15,Weapon Law Violations,Weapon Law Violations,Possessing/Concealing,Residence/Home
2,2021,2120,2021-01-21,20,Ansonia,Connecticut,18452,32,1,33,6,9,15,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Highway/Road/Alley/Street/Sidewalk
3,2021,2120,2021-01-23,13,Ansonia,Connecticut,18452,32,1,33,6,9,15,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Residence/Home
4,2021,2120,2021-01-23,13,Ansonia,Connecticut,18452,32,1,33,6,9,15,Drug Equipment Violations,Drug/Narcotic Offenses,Possessing/Concealing,Residence/Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17469,2021,2241,2021-10-22,0,Mohegan Tribal,Connecticut,0,21,4,25,2,4,6,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Gambling Facility/Casino/Race Track
17470,2021,2241,2021-10-25,5,Mohegan Tribal,Connecticut,0,21,4,25,2,4,6,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Gambling Facility/Casino/Race Track
17471,2021,2241,2021-10-25,5,Mohegan Tribal,Connecticut,0,21,4,25,2,4,6,Drug Equipment Violations,Drug/Narcotic Offenses,Possessing/Concealing,Gambling Facility/Casino/Race Track
17472,2021,2241,2021-12-15,1,Mohegan Tribal,Connecticut,0,21,4,25,2,4,6,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Gambling Facility/Casino/Race Track
17473,2021,2241,2021-12-31,22,Mohegan Tribal,Connecticut,0,21,4,25,2,4,6,Drug/Narcotic Violations,Drug/Narcotic Offenses,Possessing/Concealing,Hotel/Motel/Etc.